export const USER_SIGN = 'USER_SIGN'
export const USER_ADD_IGNORE = 'USER_ADD_IGNORE'
export const USER_REMOVE_IGNORE = 'USER_REMOVE_IGNORE'
export const USER_SUBSCRIBE = 'USER_SUBSCRIBE'
export const USER_CHANGE_AVATAR = 'USER_CHANGE_AVATAR'

export const PROFILE_SET = 'PROFILE_SET'

export const TWEET_ADD = 'TWEET_ADD'
export const TWEET_EDIT = 'TWEET_EDIT'
export const TWEET_REMOVE = 'TWEET_REMOVE'
export const TWEET_CHANGE_FAVORITE = 'TWEET_CHANGE_FAVORITE'

export const COMMENT_ADD = 'COMMENT_ADD'
export const COMMENT_REMOVE = 'COMMENT_REMOVE'
